# Generated by Django 3.1 on 2021-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
